from selenium import webdriver
import time
from selenium.webdriver.common.by import By
import yaml
from selenium.webdriver.support.select import Select
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains

with open("configuration.yaml","r") as file:
    data = yaml.safe_load(file)
    print(data)
    print(data["test2_url"])
    driver = webdriver.Chrome()
    driver.implicitly_wait(6)
    driver.maximize_window()
    driver.get(data["test2_url"])
    time.sleep(6)
    button=driver.find_element(By.XPATH,"//body/div[@id='app']/div[@class='body-height']/div[@class='home-content']/div[@class='home-body']/div[@class='category-cards']/div[3]")
    driver.execute_script("arguments[0].scrollIntoView(true);", button)
    actions = ActionChains(driver)
    actions.move_to_element(button).click(button).perform()
    time.sleep(5)
    alert=driver.find_element(By.XPATH,"//span[text()='Alerts']")
    driver.execute_script("arguments[0].scrollIntoView(true);",alert)
    actions.move_to_element(alert).click(alert).perform()
    xyz=driver.find_element(By.XPATH,"//button[@id='alertButton']")
    driver.execute_script("arguments[0].scrollIntoView(true);",xyz)
    time.sleep(5)
    actions.move_to_element(xyz).click(xyz).perform()
    acc=driver.switch_to.alert
    acc.accept()
    yzx=driver.find_element(By.XPATH,"//button[@id='timerAlertButton']")
    driver.execute_script("arguments[0].scrollIntoView(true);",yzx)
    actions.move_to_element(yzx).click(yzx).perform()
    time.sleep(5)
    acc.accept()
    zxy=driver.find_element(By.XPATH,"//button[@id='promtButton']")
    driver.execute_script("arguments[0].scrollIntoView(true);",zxy)
    actions.move_to_element(zxy).click(zxy).perform()
    time.sleep(3)
    acc.send_keys("Narendra Kumar Reddy")
    time.sleep(6)
    acc.accept()
    print("inside alerts")
    
    driver.find_element(By.XPATH,"//body/div[@id='app']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/ul[1]/li[5]").click()
    modal = driver.find_element(By.XPATH,"//button[@id='showLargeModal']")
    driver.execute_script("arguments[0].scrollIntoView(true);",modal)
    actions.move_to_element(modal).click(modal).perform()
    time.sleep(4)
    driver.find_element(By.XPATH,"//button[@id='closeLargeModal']").click()
    time.sleep(5)
    fra=driver.find_element(By.XPATH,"//span[normalize-space()='Frames']")
    driver.execute_script("arguments[0].scrollIntoView(true);",fra)
    actions.move_to_element(fra).click(fra).perform()
    print("inside frames")
    time.sleep(5)
    frame = driver.find_element(By.XPATH,"//iframe[@id='frame1']")
    driver.switch_to.frame(frame)
    dat = driver.find_element(By.XPATH,"//h1[@id='sampleHeading']")
    print(dat.text)
    driver.switch_to.default_content()
    nested = driver.find_element(By.XPATH,"//span[normalize-space()='Nested Frames']")
    driver.execute_script("arguments[0].scrollIntoView(true)",nested)
    actions.move_to_element(nested).click(nested).perform()
    print("inside nested iframes")
    frame1 = driver.find_element(By.XPATH,"//iframe[@id='frame1']")
    
    driver.switch_to.frame(frame1)
    parent = driver.find_element(By.XPATH,"//body[normalize-space(text())='Parent frame']")
    driver.execute_script("arguments[0].scrollIntoView(true)",parent)
    #actions.move_to_element(parent).click().perform()
    
    print(parent.text)
    frame2 = driver.find_element(By.XPATH,"//iframe[@srcdoc='<p>Child Iframe</p>']")
    driver.switch_to.frame(frame2)
    child = driver.find_element(By.XPATH,"//p[normalize-space()='Child Iframe']")
    driver.execute_script("arguments[0].scrollIntoView(true)",child)
    print(child.text)
    time.sleep(9)
